---

"delay": 30 #Time In Seconds

"levelname": "world"

"coal_ore": true

"iron_ore": true

"gold_ore": true

"diamond_ore": true

"emerald_ore": true

"quartz_ore": true

"redstone_ore": true

"lapis_ore": true

...

